---
title: "sports_analytics"
author: "Rick van Mil"
date: '2022-12-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(tidyverse)
library(dplyr)
library(tidyverse)
library(tidyverse)
library(StatsBombR)
library(ggsoccer)
```

```{r}
Comp <- FreeCompetitions()

ucl <- Comp %>%
  filter(competition_id==16 & season_name=="2018/2019")

matches <- FreeMatches(ucl)

events_df <- get.matchFree(matches)

clean_df <- allclean(events_df)

finale <- clean_df %>%
  filter(player.name == 'Virgil van Dijk') %>%
  filter(type.name == 'Pass')
```

```{r}
ggplot(finale) +
  annotate_pitch(dimensions = pitch_statsbomb, fill='#400D51', colour='#DDDDDD') +
  geom_segment(aes(x=location.x, y=location.y, xend=pass.end_location.x, yend=pass.end_location.y),
               colour = "coral",
               arrow = arrow(length = unit(0.15, "cm"),
                             type = "closed")) + 
  labs(title="Virgil van Dijk passing",
       subtitle="CL FINALE 2018/2019",
       caption="Data Source: StatsBomb") + 
  theme(
    plot.background = element_rect(fill='#021e3f', color='#021e3f'),
    panel.background = element_rect(fill='#021e3f', color='#021e3f'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    text = element_text(family="Geneva", color='white'),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank()
  )
```

```{r}
#Champions leugaeu finale between tottenham and liverpool

ucl<- Comp %>%
  filter(competition_id==16 & season_name=="2018/2019")
matches <- FreeMatches(ucl)

events_df <- get.matchFree(matches)

clean_df <- allclean(events_df)


Salah_pressure <- clean_df %>%
  filter(player.name == "Mohamed Salah") %>%
  filter(type.name == "Pressure")

Arnold_pressure <- clean_df %>%
  filter(player.name == "Trent Alexander-Arnold") %>%
  filter(type.name == "Pressure")
  

ggplot(Salah_pressure) +
  annotate_pitch(dimensions = pitch_statsbomb, fill='#400D51', colour='#DDDDDD') +
  geom_density2d_filled(aes(location.x, location.y, fill=..level..), alpha=0.4, contour_var='ndensity') +
  scale_x_continuous(c(0, 120)) +
  scale_y_continuous(c(0, 80)) +
  labs(title="Salah player stats",
       subtitle="UEFA Champions League Final 18/19",
       caption="Data Source: StatsBomb") + 
  theme_minimal() +
  theme(
    plot.background = element_rect(fill='#021e3f', color='#021e3f'),
    panel.background = element_rect(fill='#021e3f', color='#021e3f'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    text = element_text(family="Geneva", color='white'),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )

ggplot(Arnold_pressure) +
  annotate_pitch(dimensions = pitch_statsbomb, fill='#400D51', colour='#DDDDDD') +
  geom_density2d_filled(aes(location.x, location.y, fill=..level..), alpha=0.5, contour_var='ndensity') +
  scale_x_continuous(c(0, 120)) +
  scale_y_continuous(c(0, 80)) +
  labs(title="Alexander Arnold stats",
       subtitle="UEFA Champions League Final 18/19",
       caption="Data Source: StatsBomb") + 
  theme_minimal() +
  theme(
    plot.background = element_rect(fill='#021e3f', color='#021e3f'),
    panel.background = element_rect(fill='#021e3f', color='#021e3f'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    text = element_text(family="Geneva", color='white'),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )
```
```{r}

liverpool_shot <- clean_df %>%
  filter(type.name == 'Shot') %>%
  filter(team.name == 'Liverpool') %>%
  select(player.name, location.x, location.y, shot.end_location.x, shot.end_location.y, shot.statsbomb_xg)

tottenham_shot <- clean_df %>%
  filter(type.name == 'Shot') %>%
  filter(team.name == 'Tottenham Hotspur') %>%
  select(player.name, location.x, location.y, shot.end_location.x, shot.end_location.y, shot.statsbomb_xg)


ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb, colour='white', fill='#400D51') +
  geom_point(data=liverpool_shot, aes(x=location.x, y=location.y, size=shot.statsbomb_xg), color="red") +
  geom_point(data=tottenham_shot, aes(x=120-location.x, y=location.y, size=shot.statsbomb_xg), color="white") +
  labs(
    title="Liverpool vs Tottenham Hotspur",
    subtitle = "Shots Map | UEFA Champions League Final 2018/2019",
    caption="Data Source: StatsBomb"
  ) + 
  theme(
    plot.background = element_rect(fill='#021e3f', color='#021e3f'),
    panel.background = element_rect(fill='#021e3f', color='#021e3f'),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    text = element_text(family="Geneva", color='white'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    plot.margin = margin(2, 2, 2, 2),
    legend.position = "none"
  )
```
```{r}
shot_data_Liverpool <-clean_df %>% 

  filter(player.name %in% unique(clean_df$player.name),
         type.name == "Shot",
         team.name == "Liverpool") %>% 

  mutate(is_goal = ifelse(shot.outcome.name=="Goal", 1, 0) %>% 
           as.factor()) %>% 

  
  select(player.name, location.x, location.y, is_goal, shot.outcome.name, shot.statsbomb_xg, team.name)
 

shot_data_Tottenham<-clean_df %>% 

  filter(player.name %in% unique(clean_df$player.name),
         type.name == "Shot",
         team.name == "Tottenham Hotspur") %>% 

  mutate(is_goal = ifelse(shot.outcome.name=="Goal", 1, 0) %>% 
           as.factor()) %>% 

  
  select(player.name, location.x, location.y, is_goal, shot.outcome.name, shot.statsbomb_xg, team.name)

ggplot()+
  annotate_pitch(fill = "#400D51", dimensions = pitch_statsbomb)+
  theme_pitch()+
   theme(plot.background = element_rect(fill='#021e3f', color='#021e3f'),
         panel.background = element_rect(fill='#021e3f', color='#021e3f')) +
  coord_flip(xlim = c(60,120),
             ylim = c(0,80)) +

  geom_point(data = shot_data_Tottenham, 
             aes(x = location.x, 
                 y = location.y, 
                 colour = shot.outcome.name, 
                 size = shot.statsbomb_xg)) 
```
```{r}
shot_data_Liverpool <-clean_df %>% 

  filter(player.name %in% unique(clean_df$player.name),
         type.name == "Shot",
         team.name == "Liverpool") %>% 

  mutate(is_goal = ifelse(shot.outcome.name=="Goal", 1, 0) %>% 
           as.factor()) %>% 

  
  select(player.name, location.x, location.y, is_goal, shot.outcome.name, shot.statsbomb_xg, team.name)
 

shot_data_Tottenham<-clean_df %>% 

  filter(player.name %in% unique(clean_df$player.name),
         type.name == "Shot",
         team.name == "Tottenham Hotspur") %>% 

  mutate(is_goal = ifelse(shot.outcome.name=="Goal", 1, 0) %>% 
           as.factor()) %>% 

  
  select(player.name, location.x, location.y, is_goal, shot.outcome.name, shot.statsbomb_xg, team.name)

ggplot()+
  annotate_pitch(fill = "#400D51", dimensions = pitch_statsbomb)+
  theme_pitch()+
   theme(plot.background = element_rect(fill='#021e3f', color='#021e3f'),
         panel.background = element_rect(fill='#021e3f', color='#021e3f')) +
  coord_flip(xlim = c(60,120),
             ylim = c(0,80)) +

  geom_point(data = shot_data_Liverpool, 
             aes(x = location.x, 
                 y = location.y, 
                 colour = shot.outcome.name, 
                 size = shot.statsbomb_xg)) 
```
```{r}
ggplot()+
  annotate_pitch(fill = "#400D51",dimensions = pitch_statsbomb)+
  theme_pitch()+
  theme(plot.background = element_rect(fill='#021e3f', color='#021e3f'),
        text = element_text(family="Geneva", color='grey'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    plot.margin = margin(2, 2, 2, 2),
         panel.background = element_rect(fill='#021e3f', color='#021e3f')) +
  coord_flip(xlim = c(60,120),
             ylim = c(0,80)) +

  

  geom_point(data = shot_data_Liverpool, 
             aes(x = location.x, 
                 y = location.y, 
                 colour = shot.outcome.name, 
                 size = shot.statsbomb_xg)) +
  
 
facet_wrap(~player.name) + labs(
    title="Liverpool vs Tottenham Hotspur",
    subtitle = "Shots Liverpool | UEFA Champions League Final 2018/2019",
    caption="Data Source: StatsBomb") 
```
```{r}
ggplot()+
  annotate_pitch(fill = "#400D51",dimensions = pitch_statsbomb)+
  theme_pitch()+
  theme(plot.background = element_rect(fill='#021e3f', color='#021e3f'),
        text = element_text(family="Geneva", color='grey'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    plot.margin = margin(2, 2, 2, 2),
         panel.background = element_rect(fill='#021e3f', color='#021e3f')) +
  coord_flip(xlim = c(60,120),
             ylim = c(0,80)) +

  

  geom_point(data = shot_data_Tottenham, 
             aes(x = location.x, 
                 y = location.y, 
                 colour = shot.outcome.name, 
                 size = shot.statsbomb_xg)) +
  
 
facet_wrap(~player.name) + labs(
    title="Liverpool vs Tottenham Hotspur",
    subtitle = "Shots Tottenham | UEFA Champions League Final 2018/2019",
    caption="Data Source: StatsBomb") 
```


